PRODUCT_MIX_QUERY = """
SELECT
    THREAD_ID AS Email_Thread_ID,
    CONTENT AS Content,
    PRODUCT AS Product,
    GEN AS Gen,
    CHILD_ACCOUNT AS Retailer,
    PARENT_ACCOUNT AS Parent_Account,
    COUNTRY AS Country,
    REGION AS Region,
    REPLACE(QUARTER, '-', ' ') AS quarter_label,
    YEAR(SEND_DATE) AS year_label
FROM [BASCO_WAREHOUSE_2024].[dbo].[BASCO_AIHD_Metadata] WITH (NOLOCK)
WHERE CONTENT IS NOT NULL
  AND CONTENT NOT IN ('None', '', 'NA')
"""

HELPDESK_FEEDBACK_MERGE_QUERY = """
SELECT
    THREAD_ID,
    QUARTER,
    REPLACE(QUARTER, '-', ' ') AS quarter_label,
    REGION AS Region,
    COUNTRY AS Country,
    CHILD_ACCOUNT AS Retailer,
    CHILD_ACCOUNT AS Child_Account,
    PARENT_ACCOUNT AS Parent_Account,
    TOP_ACCOUNT_FLAG AS Top_Account,
    BRAND_ELEMENT,
    ELEMENT_FEEDBACK_CATEGORY
FROM [BASCO_WAREHOUSE_2024].[dbo].[BASCO_HELPDESK_FEEDBACK_MERGE] WITH (NOLOCK)
WHERE BRAND_ELEMENT IS NOT NULL
  AND LTRIM(RTRIM(BRAND_ELEMENT)) NOT IN ('', 'None', 'NULL')
  AND ELEMENT_FEEDBACK_CATEGORY IS NOT NULL
  AND LTRIM(RTRIM(ELEMENT_FEEDBACK_CATEGORY)) NOT IN ('', 'None', 'NULL')
"""
