VISUAL_ADOPTION_MAIN_QUERY = """
SELECT
    PARENT_ACCOUNT AS Retailer,
    COUNTRY AS Country,
    REGION AS Region,
    REPLACE(QUARTER, '-', ' ') AS quarter_label,
    ISNULL(LAYOUT_CATEGORY, 'Unknown') AS Layout_Category,
    ISNULL(GENERAL_VISUAL_STYLE, 'Unknown') AS Visual_Style,
    ISNULL(INTEL_VISUAL_FLAG, 'No') AS Intel_Visual_Flag,
    ISNULL(VISUAL_CONTENT_NAME, 'None') AS Visual_Content_Name,
    VISUAL_CONTENT_URL AS Visual_Content_URL,
    ISNULL(INTEL_VISUAL_USAGE, 'None') AS Intel_Visual_Usage,
    ISNULL(CAMPAIGN_TYPE, 'Unknown') AS Campaign_Type,
    COUNT(*) AS creative_count
FROM [BASCO_WAREHOUSE_2024].[dbo].[BASCO_AIHD_Metadata] WITH (NOLOCK)
GROUP BY
    PARENT_ACCOUNT,
    COUNTRY,
    REGION,
    QUARTER,
    LAYOUT_CATEGORY,
    GENERAL_VISUAL_STYLE,
    INTEL_VISUAL_FLAG,
    VISUAL_CONTENT_NAME,
    VISUAL_CONTENT_URL,
    INTEL_VISUAL_USAGE,
    CAMPAIGN_TYPE
ORDER BY Retailer ASC
"""

PMS_VISUALS_QUERY = """
SELECT DISTINCT
    VISUAL_CONTENT_NAME AS PMSVisual_Name,
    VISUAL_CONTENT_URL AS PMSVisual_URL,
    MIN(CONTENT) AS Content
FROM [BASCO_WAREHOUSE_2024].[dbo].[BASCO_AIHD_Metadata] WITH (NOLOCK)
WHERE VISUAL_CONTENT_NAME IS NOT NULL
  AND VISUAL_CONTENT_NAME NOT IN ('None', '', 'NA')
  AND VISUAL_CONTENT_URL IS NOT NULL
  AND VISUAL_CONTENT_URL NOT IN ('None', '', 'NA')
GROUP BY
    VISUAL_CONTENT_NAME,
    VISUAL_CONTENT_URL
ORDER BY PMSVisual_Name ASC
"""

VISUAL_USAGE_EVIDENCE_QUERY = """
SELECT
    ASSET_URL AS Asset_URL,
    ISNULL(VISUAL_CONTENT_NAME, 'None') AS Visual_Content_Name,
    VISUAL_CONTENT_URL AS Visual_Content_URL,
    PARENT_ACCOUNT AS Retailer,
    REGION AS Region,
    COUNTRY AS Country,
    REPLACE(QUARTER, '-', ' ') AS quarter_label,
    ISNULL(CAMPAIGN_NAME, ISNULL(CAMPAIGN_TYPE, 'Unknown')) AS Campaign,
    ISNULL(CONTENT, ISNULL(PRODUCT, 'Unknown')) AS Products,
    ISNULL(OFFER_FLAG, 'No') AS Offer_Flag,
    ISNULL(CTA_FLAG, 'No') AS CTA_Flag,
    ISNULL(INTEL_VISUAL_USAGE, 'None') AS Intel_Visual_Usage,
    ISNULL(LAYOUT_CATEGORY, 'Unknown') AS Layout_Category
FROM [BASCO_WAREHOUSE_2024].[dbo].[BASCO_AIHD_Metadata] WITH (NOLOCK)
WHERE ASSET_URL IS NOT NULL
  AND VISUAL_CONTENT_NAME IS NOT NULL
  AND VISUAL_CONTENT_NAME NOT IN ('None', '', 'NA')
ORDER BY SEND_DATE DESC
"""
