services:
  - type: web
    name: basco-reporting-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/auth/profile/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
