# Generated by Django 5.2.17 on 2026-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Used as the login username.",
                        max_length=254,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Full name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RSM", "Regional Sales Manager"),
                            ("RMM", "Regional Marketing Manager"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "retailer_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="RSM only: list of retailer identifier strings this RSM is responsible for.  Leave empty for RMM and Admin.",
                        verbose_name="Retailer IDs",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="RMM only: the country this RMM manages.  Leave empty for RSM and Admin.",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Required by Django admin — grants access to /admin/.",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_user",
                "ordering": ["full_name"],
            },
        ),
    ]
