# Generated by Django 5.2.17 on 2026-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RMM / Regional Leads: the geographic region (e.g. EMEA, APJ, LATAM, AMER) this user is responsible for. Leave empty for country-specific RMM or Admin.",
                max_length=100,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RMM only: the country this RMM manages.  Leave empty for RSM, Regional Leads, and Admin.",
                max_length=100,
                verbose_name="Country",
            ),
        ),
    ]
